import turtle
turtle.setup(500, 500)
# Constants value to set the flags
FLAG_WIDTH = 500
FLAG_HEIGHT = 300
STRIP_HEIGHT = 100
LEFT_X = -250
RIGHT_X = 250
TOP_Y = 150  # Half of flag
MIDDLE_Y = 50
BOTTOM_Y = -50
# Black box
turtle.penup()
turtle.goto(LEFT_X, TOP_Y)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.goto(RIGHT_X, TOP_Y)
turtle.goto(RIGHT_X, MIDDLE_Y)
turtle.goto(LEFT_X, MIDDLE_Y)
turtle.goto(LEFT_X, TOP_Y)
turtle.end_fill()
#  White box
turtle.penup()
turtle.goto(LEFT_X, MIDDLE_Y)
turtle.pendown()
turtle.color("white")
turtle.begin_fill()
turtle.goto(RIGHT_X, MIDDLE_Y)
turtle.goto(RIGHT_X, BOTTOM_Y)
turtle.goto(LEFT_X, BOTTOM_Y)
turtle.goto(LEFT_X, MIDDLE_Y)
turtle.end_fill()
# Green box
turtle.penup()
turtle.goto(LEFT_X, BOTTOM_Y)
turtle.pendown()
turtle.color("green")
turtle.begin_fill()
turtle.goto(RIGHT_X, BOTTOM_Y)
turtle.goto(RIGHT_X, -150)
turtle.goto(LEFT_X, -150)
turtle.goto(LEFT_X, BOTTOM_Y)
turtle.end_fill()
# Red triangle 
turtle.penup()
turtle.goto(LEFT_X, TOP_Y)
turtle.pendown()
turtle.color("red")
turtle.begin_fill()
turtle.goto(-50, 0) 
turtle.goto(LEFT_X, -150)
turtle.goto(LEFT_X, TOP_Y)
turtle.end_fill()
# Masjid_Dome
turtle.penup()
turtle.goto(0, -250)
turtle.setheading(0)
turtle.pendown()
turtle.color("gold")
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
#masjid_base
turtle.penup()
turtle.goto(-120, -300)
turtle.pendown()
turtle.color("dimgray")
turtle.begin_fill()
turtle.goto(120, -300)
turtle.goto(120, -150)
turtle.goto(-120, -150)
turtle.goto(-120, -300)
turtle.end_fill()
#Door 1
turtle.penup()
turtle.goto(-90, -300)
turtle.pendown()
turtle.color("lightgray")
turtle.begin_fill()
turtle.goto(-50, -300)
turtle.goto(-50, -220)
turtle.setheading(90)
turtle.circle(20, 180)
turtle.goto(-90, -300)
turtle.end_fill()
#Door 2
turtle.penup()
turtle.goto(-20, -300)
turtle.pendown()
turtle.color("lightgray")
turtle.begin_fill()
turtle.goto(20, -300)
turtle.goto(20, -220)
turtle.setheading(90)
turtle.circle(20, 180)
turtle.goto(-20, -300)
turtle.end_fill()
#Door 3
turtle.penup()
turtle.goto(50, -300)
turtle.pendown()
turtle.color("lightgray")
turtle.begin_fill()
turtle.goto(90, -300)
turtle.goto(90, -220)
turtle.setheading(90)
turtle.circle(20, 180)
turtle.goto(50, -300)
turtle.end_fill()
#slogan
turtle.penup()
turtle.goto(0, -340) 
turtle.color("black")
turtle.write("From the River to the Sea Palestine Will be Free",
             align="center",
             font=("Arial", 20, "bold"))
turtle.hideturtle()
turtle.done()